const doctorsData = [
	{
		id: 345,
		name: "Dr. Bowen Chan",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine casa",
	},
	{
		id: 346,
		name: "Dr. Samantha Lee",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Pediatrician",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
	{
		id: 347,
		name: "Dr. James Kim",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Cardiologist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine fez",
	},
	{
		id: 341,
		name: "Dr. Emily Wang",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Ophthalmologist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
	{
		id: 342,
		name: "Dr. Michael Johnson",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Dermatologist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine casa",
	},
	{
		id: 348,
		name: "Dr. Christina Chen",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Gynecologist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Fez",
	},
	{
		id: 349,
		name: "Dr. David Kim",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Neurologist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
	{
		id: 340,
		name: "Dr. Bowen Chan",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Agadir",
	},
	{
		id: 330,
		name: "Dr. Samantha Lee",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Pediatrician",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine casa",
	},
	{
		id: 331,
		name: "Dr. James Kim",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Cardiologist",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
	{
		id: 311,
		name: "Dr. Emily Wang",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Ophthalmologist",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Casa",
	},
	{
		id: 321,
		name: "Dr. Michael Johnson",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Dermatologist",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
	{
		id: 322,
		name: "Dr. Christina Chen",
		gender: "F",
		image:
			"https://t4.ftcdn.net/jpg/02/60/04/09/240_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
		speciality: [
			"Gynecologist",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "CHU SOUISSI",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Agadir",
	},
	{
		id: 360,
		name: "Dr. David Kim",
		gender: "M",
		image:
			"https://t4.ftcdn.net/jpg/03/05/41/27/360_F_305412791_XRNiWaFCREjLLpSQfj0e736foBoYXXYv.jpg",
		speciality: [
			"Neurologist",
			"Dentist",
			"Dentist",
			"OralRadiology",
			"Implantology",
			"Cosmetic",
			"Dentistry",
		],
		reviews: 120,
		degree: "DDS, DMD",
		hospital: "Hospital Ibn Sina",
		location: "Rabat",
		experience: 5,
		education: "faculte de medecine Rabat",
	},
];

export default doctorsData;
